[WIP] Add juju cluster type to support juju managed clouds.
chanchiwai-ray/sos pull request #1
Opened 2023-03-31 12:12 UTC by chanchiwai-ray

---
Please place an 'X' inside each '[]' to confirm you adhere to our [Contributor Guidelines](https://github.com/sosreport/sos/wiki/Contribution-Guidelines)

- [ ] Is the commit message split over multiple lines and hard-wrapped at 72 characters?
- [ ] Is the subject and message clear and concise?
- [ ] Does the subject start with **[plugin_name]** if submitting a plugin patch or a **[section_name]** if part of the core sosreport code?
- [ ] Does the commit contain a **Signed-off-by: First Lastname <email@example.com>**?
- [ ] Are any related Issues or existing PRs [properly referenced](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) via a Closes (Issue) or Resolved (PR) line?

2023-03-31 13:12 UTC, esunar requested changes

2023-03-31 13:12 UTC, esunar commented on sos/collector/clusters/juju.py
> +# Copyright Red Hat 2020, Jake Hunsaker <jhunsake@redhat.com>
Change copyright

2023-03-31 13:12 UTC, nicolasbock commented on sos/collector/clusters/juju.py
> +# Copyright Red Hat 2020, Jake Hunsaker <jhunsake@redhat.com>
Copyright?

2023-04-03 03:37 UTC, chanchiwai-ray commented on sos/collector/clusters/juju.py
> +# Copyright Red Hat 2020, Jake Hunsaker <jhunsake@redhat.com>
DONE

2023-04-03 03:37 UTC, chanchiwai-ray commented on sos/collector/clusters/juju.py
> +# Copyright Red Hat 2020, Jake Hunsaker <jhunsake@redhat.com>
DONE

2023-04-04 08:26 UTC, pponnuvel reviewed
With the default being collecting sos on all applications, one potential concern is the size of resulting sos. In a large model, this could be massive. The user may not be able to predict the total size, so may not realise they need filters.

I suppose this isn't a particularly new problem (any sos collection can run into this). But it can be more pronounced here. As long as the Juju client 'running out of space' isn't going to affect access/working of apps in a model, I think this should be fine.

2023-04-04 08:26 UTC, pponnuvel commented on sos/collector/clusters/juju.py
> +        ("models", "", "Filter node list by moedls (comma separated)."),
Typo: `moedls` -> `models`

2023-04-04 08:26 UTC, pponnuvel commented on sos/collector/clusters/juju.py
> +            raise Exception(f"{status_cmd} did not return usable output")
Do you also want to log this say with `self.log_debug` or `self.log_error`?

2023-04-04 08:55 UTC, pponnuvel reviewed
With the default being collecting sos on all applications, one concern is the size of resulting sos. In a large model, this could be massive and user may not realise they have to to use filters.

I suppose this isn't a particularly new problem (any sos collection can run into this). But it can be more pronounced here. As long as Juju client running out of space isn't going to affect access to/functionality of model, I think this should be fine.

2023-04-04 11:40 UTC, closed without merging